mkcert: mkcert.c
	gcc -o mkcert mkcert.c -I/opt/homebrew/Cellar/openssl@3/3.2.0_1/include -L/opt/homebrew/Cellar/openssl@3/3.2.0_1/lib -lcrypto
verifycert: verifycert.c
	gcc -o verifycert verifycert.c -I/opt/homebrew/Cellar/openssl@3/3.2.0_1/include -L/opt/homebrew/Cellar/openssl@3/3.2.0_1/lib -lcrypto